# fly.toml app configuration file generated for ecommercedotnet-portfolioahl92 on 2023-11-02T13:23:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecommercedotnet-portfolioahl92"
primary_region = "mia"

[build]
  image = "ahernandez92/ecommercereactdotnet"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__Publishablekey = "pk_test_51MpGaLGVq1NalTujdlqoNF1nf2Rbc1hT0Z51XmnD8WEo1kYXIAmaYcCuQE8r3ENv5JEhGiqDrlj2EoS1Lt46Lkpm00xemzwV4V"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
